# Generated by Django 5.2 on 2025-04-15 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_problema', models.CharField(choices=[('A', 'Alagamento'), ('B', 'Buraco'), ('L', 'Lixo'), ('O', 'Outro')], default='O', max_length=1)),
                ('descricao', models.TextField(help_text='Descrição detalhada do problema')),
                ('foto', models.ImageField(blank=True, help_text='Foto do local do relato', null=True, upload_to='relatos_fotos/')),
                ('poligono', models.JSONField(help_text='Formato: lista de pares [lat, lng] ou GeoJSON')),
                ('data_relato', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Em Análise'), ('R', 'Resolvido')], default='P', max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relato',
                'verbose_name_plural': 'Relatos',
                'ordering': ['-data_relato'],
            },
        ),
    ]
