# Generated by Django 5.2 on 2025-04-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relato',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
    ]
