# Generated by Django 5.2 on 2025-04-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportar', '0002_relato_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relato',
            old_name='tipo',
            new_name='ponto',
        ),
    ]
