# Generated by Django 5.2 on 2025-04-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportar', '0003_rename_tipo_relato_ponto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relato',
            name='ponto',
        ),
    ]
