# Generated by Django 5.0.5 on 2025-04-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportar', '0004_remove_relato_ponto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relato',
            name='tipo_problema',
            field=models.CharField(choices=[('A', 'Alagamento'), ('B', 'Buraco'), ('L', 'Lixo'), ('I', 'Iluminação'), ('S', 'Saneamento'), ('O', 'Outro')], default='O', max_length=1),
        ),
    ]
