# Generated by Django 5.0.5 on 2025-04-28 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='animais/')),
                ('data_resgate', models.DateTimeField(auto_now_add=True)),
                ('data_adocao', models.DateTimeField()),
                ('adotado', models.BooleanField(default=False)),
                ('adotado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_adotou', to=settings.AUTH_USER_MODEL)),
                ('resgatado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resgatou', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
