# Generated by Django 5.0.5 on 2025-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resgate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='data_adocao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
